In [16]:
import numpy as np 

In [17]:
# creating an array in 2D
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [18]:
#similar process in division
a*2

array([[2, 4],
       [6, 8]])

In [19]:
#similar process in addition
print(a-3) 

[[-2 -1]
 [ 0  1]]


In [43]:
# linspace spaced a number over a specified interval
# num gives the number of elements to be generated in interval
b = np.linspace(5,8, num=4)
b

array([ 5.,  6.,  7.,  8.])

In [36]:
# array will be reshape in form of 2* 2 
b = b.reshape(2,2)
b

array([[ 5.,  6.],
       [ 7.,  8.]])

In [21]:
# element wise operation, for all airthmatic oprtaion it will same.
print(a*b)

[[ 5 12]
 [21 32]]


In [22]:
#matrix multiplication 
print (a.dot(b))

[[19 22]
 [43 50]]


In [23]:
#horizontally stacking  of two matrices
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [24]:
#vertically stacking of two matrices
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
# unpack the array into 1d elements and then append them
c = np.append(a,b)
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
# working as vertical stacking
c = np.append(a,b,axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
# working as horizontal  stacking

c = np.append(a,b, axis=1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [41]:
# indexing the element 
c[0][2]


5

In [37]:
# print the element at position [0,2] but similar to above syntax
c[0,2]


5

In [38]:
# printing all the elemts in row 1
c[0,:]

array([1, 2, 5, 6])

In [39]:
#printing all the elements in coulumn 1
c[:,0]

array([1, 3])

In [40]:


c[:,1:3]

array([[2, 5],
       [4, 7]])